export const instructors = [
  {
    key: "Loida D. Rivera",
    label: "Loida D. Rivera",
  },
  {
    key: "Gary C. Santos",
    label: "Gary C. Santos",
  },
  { key: "Airon Ivan A. Santos", label: "Airon Ivan A. Santos" },
  { key: "Marlon Espidellon", label: "Marlon Espidellon" },
  { key: "Catherine Tosino", label: "Catherine Tosino" },
  { key: "Fernando Camacho", label: "Fernando Camacho" },
  { key: "Richelle Gadaingan", label: "Richelle Gadaingan" },
  { key: "Chel Bonito", label: "Chel Bonito" },
  { key: "Elaiane Joy Gadicho", label: "Elaiane Joy Gadicho" },
  { key: "Floyd John Barbin", label: "Floyd John Barbin" },
  { key: "Gideon Guitonez", label: "Gideon Guitonez" },
  { key: "Hannah H. Ruaza", label: "Hannah H. Ruaza" },
  { key: "Jamaica Herrera", label: "Jamaica Herrera" },
  { key: "Jerryson Villa", label: "Jerryson Villa" },
  { key: "Jhun Hernandez", label: "Jhun Hernandez" },
  { key: "Joseph Reyes", label: "Joseph Reyes" },
  { key: "Judy Garcia", label: "Judy Garcia" },
  { key: "Junels Reg", label: "Junels Reg" },
  { key: "Leilani R. Sangalang", label: "Leilani R. Sangalang" },
  { key: "Mac Claricia", label: "Mac Claricia" },
  { key: "Maricar O. Dupal-ag", label: "Maricar O. Dupal-ag" },
  { key: "Mell Tolentino", label: "Mell Tolentino" },
  { key: "Mellany Ann Corneja", label: "Mellany Ann Corneja" },
  { key: "Regine Sa", label: "Regine Sa" },
  { key: "Shearyl Cuaderno", label: "Shearyl Cuaderno" },
];
