import { Button } from "@nextui-org/react";
import { useMemo } from "react";
import { User } from "@nextui-org/user";
import { getAllApprovedUsersData } from "@/backendapi/user";
import { useLoaderData } from "react-router-dom";
import jsPDF from "jspdf";
import logo from "@/assets/redcross_logo.png";

interface User {
  _id: string;
  firstname: string;
  lastname: string;
  email: string;
  address: string;
  orNumber: number;
  contact: string;
  gender: string;
  password: string;
  userType: string;
  certificateApproved: boolean;
  profilePictureUrl: string;
  certificateUrl: string;
  category: string;
  dateStarted: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

type Users = {
  users: User[];
};

export const loader = async () => {
  let users = await getAllApprovedUsersData();
  return { users };
};

const Archives = () => {
  const { users } = useLoaderData() as Users;

  const groupedUsers = useMemo(() => {
    return users.reduce<{ [key: string]: User[] }>((acc, user) => {
      const date = new Date(user.updatedAt).toLocaleDateString("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric",
      });
      if (!acc[date]) {
        acc[date] = [];
      }
      acc[date].push(user);
      return acc;
    }, {});
  }, []);

  const handleDownload = (date: string, users: User[]) => {
    const doc = new jsPDF();

    // Header setup
    const headerTitle = `User Report - ${date}`;
    const headerSubtitle = "Generated by Red Cross Cavite";
    const reportDate = `Report Date: ${new Date().toLocaleDateString("en-US")}`;
    const headerYPosition = 10;

    // Add logo
    const logoWidth = 30;
    const logoHeight = 23;
    doc.addImage(logo, "PNG", 10, 15, logoWidth, logoHeight);

    // Add header text
    doc.setFontSize(16);
    doc.text(headerTitle, 50, headerYPosition + 10);
    doc.setFontSize(12);
    doc.text(headerSubtitle, 50, headerYPosition + 18);
    doc.text(reportDate, 50, headerYPosition + 26);

    // Table setup with narrower margins
    const startY = 50;
    const rowHeight = 10;
    const pageWidth = doc.internal.pageSize.getWidth();
    const sideMargin = 10; // Narrower than before
    const tableWidth = pageWidth - 2 * sideMargin;
    const colWidths = [
      tableWidth * 0.25,
      tableWidth * 0.35,
      tableWidth * 0.2,
      tableWidth * 0.2,
    ];
    const centerX = sideMargin;

    const columns = ["Name", "Email", "Address", "Category"];
    let currentY = startY;

    // Draw header row
    doc.setFontSize(10);
    doc.setFillColor(255, 0, 0);
    doc.setTextColor(255, 255, 255);
    doc.rect(centerX, currentY, tableWidth, rowHeight, "F");
    let currentX = centerX;
    columns.forEach((col, i) => {
      doc.text(col, currentX + 2, currentY + 7);
      currentX += colWidths[i];
    });

    currentY += rowHeight;
    doc.setTextColor(0, 0, 0);

    // Draw rows
    users.forEach((user, index) => {
      currentX = centerX;
      const fullName = `${user.firstname} ${user.lastname}`;
      const row = [fullName, user.email, user.address, user.category];

      // Alternate row background
      if (index % 2 === 0) {
        doc.setFillColor(240, 240, 240);
        doc.rect(centerX, currentY, tableWidth, rowHeight, "F");
      }

      row.forEach((cell, i) => {
        const textLines = doc.splitTextToSize(cell, colWidths[i] - 4); // Wrap text inside cell
        doc.text(textLines, currentX + 2, currentY + 7);
        currentX += colWidths[i];
      });

      currentY += rowHeight;
      if (currentY > 280) {
        doc.addPage();
        currentY = startY;
      }
    });

    doc.line(centerX, currentY, centerX + tableWidth, currentY);
    doc.save(`User_Report_${date.replace(/ /g, "_")}.pdf`);
  };

  return (
    <div className="flex flex-col gap-5">
      <h2>Archives</h2>
      <div className="grid grid-cols-6 gap-3">
        {Object.keys(groupedUsers).map((date) => (
          <Button
            key={date}
            onClick={() => handleDownload(date, groupedUsers[date])}
          >
            {date}
          </Button>
        ))}
      </div>
    </div>
  );
};

export default Archives;
